services:
  - type: web
    name: mini-natsu-md
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /
    envVars:
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_OWNER
        value: "natsu242"
      - key: GITHUB_REPO
        value: "dentsu-xmd-v7"
      - key: PORT
        value: "10000"
